### ISSUE TITLE
Can't add Trello card to channel

### ISSUE THREAD

**Issue by jayoshih** [learningequality/sushibar#191]
When I try to add a card to the [Saylor Channel](https://sushibar.learningequality.org/runs/362c457d-00d6-476d-97f1-e76743f9169e/#summary), it returns the following error

<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="x-ua-compatible" content="ie=edge"> <link rel="shortcut icon" href="/static/images/sushi.png"> <title>Server Error</title> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta name="description" content=""> <meta name="author" content="">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  <link rel="stylesheet/less" type="text/css" href="/static/less/base.less" /> <link rel="stylesheet/less" type="text/css" href="/static/less/users.less" /> <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&amp;subset=latin-ext" rel="stylesheet"> </head> <body> <div class="container" id="sushi-wrapper"> <nav class="navbar navbar-toggleable-md navbar-default navigation-clean-search"> <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar-items" aria-controls="navbar-items" aria-expanded="false" aria-label="Toggle navigation"> <i class="fa fa-bars"></i> </button> <a class="navbar-brand navbar-link" href="/"><img src="/static/images/sushi.png" id="sushi-icon">Sushi Bar</a> <div class="collapse navbar-collapse" id="navbar-items"> <form id="search-form" class="form-inline"> <div class="input-group mb-2 mr-sm-2 mb-sm-0"> <input type="text" class="form-control typeahead" placeholder="Search..." aria-label="Search" aria-describedby="search-icon" id="search-input"> <span class="input-group-addon" id="search-icon"><i class="fa fa-search"></i></span> </div> </form> <ul class="nav navbar-nav ml-auto w-100 justify-content-end"> <li class="nav-item"> <a id="log-in-link" class="nav-link" href="/signin/">Sign In</a> </li> </ul> </div> </nav> <h1>Ooops!!! 500</h1> <h3>Looks like something went wrong!</h3> <p>We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.</p> <div class="footer-basic"> <hr> <footer> <a href="http://contentworkshop.learningequality.org" target="_blank">Kolibri Studio&nbsp;·</a> <a href="https://github.com/learningequality/ricecooker" target="_blank">&nbsp;Ricecooker&nbsp;·</a> <a href="https://github.com/learningequality/sushibar" target="_blank">&nbsp;Github</a> <p class="copyright"><a href="https://learningequality.org" target="_blank">Learning Equality © 2017</a></p> </footer> </div> </div>    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script> <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>  <script src="/static/js/typeahead.bundle.min.js"></script>  <script src="/static/js/project.js"></script> <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script> </body> </html>

**Comment by ivanistheone** [comment]
from the logs
```
ERROR 2018-07-09 17:45:35,919 exception 89 140044886513408 Internal Server Error: /services/trello/abb570d1fc715d198b43716113d9b8de/save_trello_url/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/sushibar/services/trello/api.py", line 255, in post
    channel = ContentChannel.objects.get(channel_id=channel_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
    (self.model._meta.object_name, num)
sushibar.runs.models.MultipleObjectsReturned: get() returned more than one ContentChannel -- it returned 26!
```
